-- Staff moderator roles: Event Manager, User Manager, Main Moderator
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'EVENT_MANAGER';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'USER_MANAGER';
ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'MAIN_MODERATOR';
